wallet: "wallet.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
contractHash: "686264f6112ec344f818a139937be94ff6271321"
storage_node: "localhost:8080"
storage_container: "9iEiK7H3xC7Q9X9R1rSqRFLKXfsxYweos4NyrAmHMTid"
listen_address: ":"