wallet: "backend/wallet3.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
goofyahhdocuments_contract: "d487b1f344c783d9275fbc3fcc15fc5209aa6388"
storage_node: "localhost:8080"
storage_container: "HRnXPvSEuaZttVSmSADKJvvbBsp9o4swKEtmnD2avVxp"
listen_address: ":5555"