wallet: "wallet.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
contractHash: "954b291a491004172c83f7ab1b4f2a94a8150789"
storage_node: "localhost:8080"
storage_container: "9iEiK7H3xC7Q9X9R1rSqRFLKXfsxYweos4NyrAmHMTid"
listen_address: ":2221"