wallet: "backend/wallet.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
goofyahhdocuments_contract: "65366b2eea5336a63b05e0ae57ea493558426aef"
storage_node: "localhost:8080"
storage_container: "3eP8dTNvqELPMBbgZMyVi8bk88yzKsLLtZcZnkRN7AwK"
listen_address: ":5525"